### ISSUE TITLE
With Chrome prototype, setting a manual FPS should bypass any 3p cookies block

### ISSUE THREAD

**Issue by hpsin** [cfredric/sameparty#4]
A specific goal of testing FPS is to ensure that FPS will help our apps continue working when 3p cookies are blocked (either via the default Incognito setting or in the Privacy Sandbox future where all 3p cookies are blocked).  

This is called out in the explainer:

> SameParty cookies are subject to the same user-controlled third-party cookie blocking settings as other cookies, during this initial prototype phase in Chrome. If a user has third-party cookie blocking enabled globally or for a specific site, cookies will not be sent in a cross-site context, regardless of the presence of SameParty. This behavior is intended for the initial prototype because we believe it aligns with users’ current expectations with respect to their privacy controls. 

This is entirely cogent for normal users who could be subjected to Origin Trials.  However, for developers specifically testing for how/if FPS can help their site, this change in behavior blocks useful testing. 

**Ask**: a developer who has gone to about:flags and set their own FPS has very specific expectations about behaviors here, that are different from a standard user's.  Thus, in the case above, SameParty cookies should bypass 3p cookie blocks.  

Thanks,
Hirsch

**Comment by cfredric** [comment]
Thanks for the suggestion! We agree that it's important to provide developers a way to test that behavior. We'll introduce a new flag for opting in to treating SameParty cookies as first-party, rather than third-party.

However, in order to preserve the way for developers to test the behavior their users would get if they participated in the origin trial, we will **not** enable the new flag automatically when `--use-first-party-set` is in use.

I'll keep this issue open until the new flag has been implemented.

**Comment by hpsin** [comment]
Thanks! I think that makes sense, appreciate it!

**Comment by cfredric** [comment]
I've added a `--sameparty-cookies-considered-first-party` flag to enable this testing, disabled by default. This flag will be available in Chrome 93 (https://chromiumdash.appspot.com/schedule).

(Chromium tracking bug: https://crbug.com/1203706)
